[auth]
redirect_uri="https://edwardpriyatna-auth0-test-applanding-nkditt.streamlit.app/oauth2callback"
cookie_secret="eb01f061b231681f1f6da1b30284b0bbf3992eda34d416a907964d937d8dee81"

[auth.auth0]
domain = "dev-1yjtdfcmy4tkj356.us.auth0.com"
client_id = "plvvlym9zkw0BEN6C0ZTLM1NlqFysxHV"
client_secret = "UXtAQ_N2_tb3dJ-ogUAKu1fFx18u4GU0Vyc8zjU7sCSRxkhuZ3YoylzRag3ZujPl"
server_metadata_url="https://dev-1yjtdfcmy4tkj356.us.auth0.com/.well-known/openid-configuration"