[auth]
redirect_uri="https://logging-in-test-edward.streamlit.app/oauth2callback"
cookie_secret="eb01f061b231681f1f6da1b30284b0bbf3992eda34d416a907964d937d8dee81"

[auth.auth0]
domain = "dev-1yjtdfcmy4tkj356.us.auth0.com"
client_id = "BZM8zg5zKD9ia6ov2kErcyJaLoA9RMUa"
client_secret = "15VDLfh5sfXbyodZLWeyDLd0520seTLjPKFwPuECY-qjk0ORahqnOEQfSppDYBi4"
server_metadata_url="https://dev-1yjtdfcmy4tkj356.us.auth0.com/.well-known/openid-configuration"