[auth]
redirect_uri="http://localhost:8501/oauth2callback"
cookie_secret="eb01f061b231681f1f6da1b30284b0bbf3992eda34d416a907964d937d8dee81"

[auth.auth0]
domain = "mydomain.auth0.com"
client_id = "1058335871386-vpnqtrkeljgk2ssv0sbsfiksq8vvr8jo.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url="https://<DOMAIN>.<REGION>.auth0.com/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }