[auth]
redirect_uri = "https://edwardpriyatna-auth0-test-app-jyp446.streamlit.app/oauth2callback
cookie_secret="174ace16611bd57c536d34d80f3599d5e57660ab9abcf2a9d63992523200696e"

[auth.google]
client_id="1058335871386-vpnqtrkeljgk2ssv0sbsfiksq8vvr8jo.apps.googleusercontent.com"
client_secret="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"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"